### ISSUE TITLE
Error from calc_channel_width in Step2_MeasureChannelWidth.py

### ISSUE THREAD

**Issue by benrsellers** [rmichie/TTools#1]
I am able to successfully run Step1_SegmentStream.py, but getting the following error while running Step2_MeasureChannelWidth.py:

```
PYTHON ERRORS:
Traceback (most recent call last):
  File "<string>", line 243, in <module>
  File "<string>", line 139, in calc_channel_width
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\arcobjects\arcobjects.py", line 859, in distanceTo
    return convertArcObjectToPythonObject(self._arc_object.DistanceTo(*gp_fixargs((other,))))
ValueError: <geoprocessing describe geometry object object at 0x22DB9A00>

Error Info:
<geoprocessing describe geometry object object at 0x22DB9A00>
```

**Comment by coltenelkin** [comment]
Ran into this same error and fixed it by setting up the calc_channel_width() function to handle the edge case where the generated line that goes from the node out +/- 90 degrees from the azimuth does not intersect the right or left bank feature geometry.

The error stems from the fact that the pt2 object created by intersecting the created line and the (left or right) bank doesn't have any features or a centroid, so there's nothing to measure to.

Try copying the below code and using it to replace the original calc_channel_width() function in Step 2. If there's not an intersection, I have the line rotate about the node until it does intersect the bank geometry; it performs the rotation twice (once clockwise and once counter-clockwise) and records the distance from the node to the bank for each rotation. The lesser of the two distances is reported out as the distance from the node to the (left or right) bank.

```
def calc_channel_width(node_geom, bank_geom, aspect, line_dis, proj_nodes):
    pt1 = node_geom.pointFromAngleAndDistance(aspect, line_dis, "PLANAR")
    line = arcpy.Polyline(arcpy.Array([node_geom.centroid, pt1.centroid]), proj_nodes)
    pt2 = line.intersect(bank_geom, 1)
    aspectAttempt = aspect # allows us to rotate the line without touching the original aspect
    aspectIncrementerSwitch = False # this line helps us choose which distance to return at the end of the function
    if not pt2.centroid: # if there's no intersection enter this loop
        aspectIncrementerSwitch = True # turn on the rotation switch to return the correct distance
        while not pt2.centroid: # added by CME in June 2023. Had to deal with an edge case where the generated line never intersected the right bank or left bank
                                # ...first we try decrementing and getting that distance
            aspectAttempt = aspectAttempt - 1
            if aspectAttempt < 0:
                aspectAttempt = aspectAttempt + 360
            pt1 = node_geom.pointFromAngleAndDistance(aspectAttempt, line_dis, "PLANAR")
            line = arcpy.Polyline(arcpy.Array([node_geom.centroid, pt1.centroid]), proj_nodes)
            pt2 = line.intersect(bank_geom, 1)
        to_bank_distance_1 = node_geom.distanceTo(pt2)
        del pt2
        pt1 = node_geom.pointFromAngleAndDistance(aspect, line_dis, "PLANAR")
        line = arcpy.Polyline(arcpy.Array([node_geom.centroid, pt1.centroid]), proj_nodes)
        pt2 = line.intersect(bank_geom, 1)
        aspectAttempt = aspect
        while not pt2.centroid: # now we reset and try incrementing the angle (moving clockwise)
            aspectAttempt = aspectAttempt + 1
            if aspectAttempt < 360:
                aspectAttempt = aspectAttempt - 360
            pt1 = node_geom.pointFromAngleAndDistance(aspectAttempt, line_dis, "PLANAR")
            line = arcpy.Polyline(arcpy.Array([node_geom.centroid, pt1.centroid]), proj_nodes)
            pt2 = line.intersect(bank_geom, 1)
        to_bank_distance_2 = node_geom.distanceTo(pt2)
        
    if not aspectIncrementerSwitch: # if we didn't have to rotate and increment the aspect, just report out the distance
        to_bank_distance = node_geom.distanceTo(pt2)
    else:
        to_bank_distance = min(to_bank_distance_1, to_bank_distance_2) # if we had to rotate, compare the two distances and take the lesser

    return (to_bank_distance)
```
